### ISSUE TITLE
Runaway Exception

### ISSUE THREAD

**Issue by ReddyFreddy** [reddcoin-project/reddcoin#2] opened 2022-03-23 22:37 UTC
Windows
Closed App during initial sync

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	reddcoin-qt.exe
  Application Version:	22.0.0.0
  Application Timestamp:	00000000
  Fault Module Name:	reddcoin-qt.exe
  Fault Module Version:	22.0.0.0
  Fault Module Timestamp:	00000000
  Exception Code:	c0000005
  Exception Offset:	0000000001337829
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	c28f
  Additional Information 2:	c28fa8c153da28baa5edb1d90de4f359
  Additional Information 3:	9855
  Additional Information 4:	985538ec05d5ce4e9c04d681bd4b3512

debug:

2022-03-23T22:35:33Z ERROR: AcceptBlockHeader: prev block not found
2022-03-23T22:39:57Z tor: Thread interrupt
2022-03-23T22:39:57Z ThreadStakeMinter interrupted
2022-03-23T22:39:57Z

EXCEPTION: St12system_error
Invalid argument
C:\Program Files\Bitcoin\reddcoin-qt.exe in Runaway exception

2022-03-23T22:39:57Z torcontrol thread exit

2022-03-23T22:50:47Z tor: Thread interrupt
2022-03-23T22:50:47Z ThreadStakeMinter interrupted
2022-03-23T22:50:47Z

EXCEPTION: St12system_error
Invalid argument
C:\Program Files\Bitcoin\reddcoin-qt.exe in Runaway exception

2022-03-23T22:50:47Z torcontrol thread exit

- END DEBUG

Any syncing progress is lost. Syncing starts over from the beginning.

After this receiving error, if wallet is restarted without a windows reboot, syncing becomes extraordinarily slow and may fail and stop progressing.

Restarting windows seems to alleviate the issue.

**Comment by ReddyFreddy** [comment] 2022-03-23 22:57
Any syncing progress is lost. Syncing starts over from the beginning.

After this receiving error, if wallet is restarted without a windows reboot, syncing becomes extraordinarily slow and may fail and stop progressing. 

Restarting windows seems to alleviate the issue.

**Comment by ReddyFreddy** [comment] 2022-03-23 23:45
2022-03-23T22:35:33Z ERROR: AcceptBlockHeader: prev block not found
2022-03-23T22:39:57Z tor: Thread interrupt
2022-03-23T22:39:57Z ThreadStakeMinter interrupted
2022-03-23T22:39:57Z 

************************
EXCEPTION: St12system_error       
Invalid argument       
C:\Program Files\Bitcoin\reddcoin-qt.exe in Runaway exception       

2022-03-23T22:39:57Z torcontrol thread exit




2022-03-23T22:50:47Z tor: Thread interrupt
2022-03-23T22:50:47Z ThreadStakeMinter interrupted
2022-03-23T22:50:47Z 

************************
EXCEPTION: St12system_error       
Invalid argument       
C:\Program Files\Bitcoin\reddcoin-qt.exe in Runaway exception       

2022-03-23T22:50:47Z torcontrol thread exit

**Comment by ReddyFreddy** [comment] 2022-03-24 04:45
Happened again. This time wallet was fully synced.
Afterwards, had to sync again from the beginning. 

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	reddcoin-qt.exe
  Application Version:	22.0.0.0
  Application Timestamp:	00000000
  Fault Module Name:	reddcoin-qt.exe
  Fault Module Version:	22.0.0.0
  Fault Module Timestamp:	00000000
  Exception Code:	c0000005
  Exception Offset:	0000000001337829
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	c28f
  Additional Information 2:	c28fa8c153da28baa5edb1d90de4f359
  Additional Information 3:	9855
  Additional Information 4:	985538ec05d5ce4e9c04d681bd4b3512

DEBUG:
2022-03-24T04:39:30Z UpdateTip: new best=4ba65942cd835fcb5690652a51534864d033339ab07f59d52e91b2b67e0439fd height=91028 version=0x00000005 log2_work=53.547715 tx=180620 date='2022-03-24T04:39:30Z' progress=1.000000 cache=40.6MiB(260811txo)
2022-03-24T04:41:51Z tor: Thread interrupt
2022-03-24T04:41:51Z ThreadStakeMinter interrupted
2022-03-24T04:41:51Z torcontrol thread exit
2022-03-24T04:41:51Z 

************************
EXCEPTION: St12system_error       
Invalid argument       
C:\Program Files\Bitcoin\reddcoin-qt.exe in Runaway exception

**Comment by reddink** [comment] 2022-03-28 02:28
This looks like the staking thread not being closed correctly

**Comment by barrystyle** [comment] 2022-05-23 18:27
Staking thread hang was confirmed resolved in ef5e4c9

**Closed as completed by barrystyle** 2022-05-23 18:27 UTC
Labels: bug
